### ISSUE TITLE
.NET Core Support?

### ISSUE THREAD

**Issue by soccermitchy** [exaphaser/SharpJS#4]
Trying to develop a SharpJS test thing using .net core, yet when I do 'dotnet restore', I get this:
```
mitchell@ubuntu:~/code/thing$ dotnet restore
log  : Restoring packages for /home/mitchell/code/thing/project.json...
log  : Installing SharpJS 1.6.3.
error: Package SharpJS 1.6.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package SharpJS 1.6.3 supports: net (.NETFramework,Version=v0.0)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
log  : Writing lock file to disk. Path: /home/mitchell/code/thing/project.lock.json
log  : /home/mitchell/code/thing/project.json
log  : Restore failed in 10808ms.

Errors in /home/mitchell/code/thing/project.json
    Package SharpJS 1.6.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package SharpJS 1.6.3 supports: net (.NETFramework,Version=v0.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

Here's my project.json:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true,
    "copyToOutput": { "includeFiles": ["html"] }
  },
  "dependencies": {
    "SharpJS": "1.6.3"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

If I try to add an import for '.NETFrameworkv0.0', the package does install, but does not build (presumably because SharpJS is compiled w/ .net 4.5? not sure)

**Comment by 0xFireball** [comment]
Hello!

I'm happy to see interest in SharpJS!

As for your problem, I did not have .NET Core in mind when putting together SharpJS. Yes, SharpJS is currently compiled for .NET 4.5.

However, I do think that .NET Core support would be great, as it would make SharpJS more portable, so thanks for bringing this to my attention!
I will soon start working on updating the reference libraries from .NET 4.5 to .NET Core; this will allow users of the library to build their apps for .NET Core!

Unfortunately, it would not be as straightforward to actually port the compiler to .NET Core, because it is built on JSIL, which uses the standard .NET Framework.

The end result would be:
1) You can use SharpJS with .NET Core (compilation)
2) You still need `mono` to actually run the SharpJS compiler

Let me know if this works? If not, we can think of alternate solutions?

**Comment by soccermitchy** [comment]
I was able to get it to build with this project.json, but now it doesn't run. Trying to find a way to get .NET Core to put the dependencies in the output directory...
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true,
    "copyToOutput": { "includeFiles": ["html"] }
  },
  "dependencies": {
    "SharpJS": "1.6.3"
  },
  "frameworks": {
    "net452": {
    }
  }
}
```

**Comment by 0xFireball** [comment]
Can you give some more information as to why it "doesn't run?"
The NuGet package actually uses mono to run `JSILc` on your compiled assembly, so that might very well be your issue.

I recommend that for your actual SharpJS project, you use Xamarin Studio/MonoDevelop (if you're not on windows) or Visual Studio (if you are on Windows). The build process currently requires some .NET/Mono specific tooling. SharpJS works well on Visual Studio and on Xamarin Studio.

If you want templates for visual studio, you can get it from the official page:
https://exaphaser.github.io/SharpJS/

A quickstart with Visual Studio: https://exaphaser.github.io/SharpJS/#quickstart

**Comment by soccermitchy** [comment]
Problem I just noticed with that solution: only works on windows, defeating the purpose of me doing that... I'm trying to avoid having to go through and making project.json files for everything. Also, not doing this for an actual project, just to see if it's possible to make this work with .net core, and the error I was getting was because of it not copying dependencies. (don't remember the exact error, but it was something about it not finding the webforms dll)

**Comment by soccermitchy** [comment]
To emphasize on "only works on windows":  It doesn't build on Linux because it's looking for .net 4.5.2, which isn't on linux. (it doesn't look for mono)

**Comment by 0xFireball** [comment]
Unfortunately, SharpJS was never designed with `dotnet` in mind. It was designed for the CLR or Mono with MSBuild/XBuild. It should work just fine on Linux, but you will have to use 
1) the manual template (https://github.com/exaphaser/SharpJS/tree/master/VSAddin/ExaPhaser.SharpJS.Addins/WebFormsTemplate)
2) mono with msbuild/xbuild, not dotnet

**Comment by soccermitchy** [comment]
Yep, I've gotten that setup working already, my main issue with that way of doing it is that it is a pain to do things like add files to the project from the command line, and MonoDevelop sucks up all my ram (used about 3-4gb of ram), so starting it just to, say, add a file to a project is not a very good way of doing it, while with a .net core project, just having a file in a directory works as adding it... 

How often is the stable version of SharpJS updated? I'd be interested in maintaining my own fork of it that has full dotnet support and keeping it up to date with the stable branch. ("full dotnet support" in this case including things like being able to do, say, `dotnet deploy -c release` to deploy the project to a server, ie. over ftp/sftp)

**Comment by 0xFireball** [comment]
@soccermitchy I'd be interested in merging both versions together, I'd be happy to take a pull request, so we can keep everything together!



You don't actually have to use MonoDevelop, as I mentioned earlier, you can just use `git` to download the template, then `cp` it to your project dir. Then use `mono nuget.exe` to restore NuGet packages, and `xbuild`  to build `csproj` and `sln`

**Comment by soccermitchy** [comment]
Problem there is that I still can't do basic tasks with the project files like adding files to a project.

**Comment by 0xFireball** [comment]
@soccermitchy I see.

It would be great if you could send a pull request from a fork with the `dotnet` support.

**Comment by soccermitchy** [comment]
Sweet, I'll start working on that either later tonight or tomorrow.

**Comment by 0xFireball** [comment]
@soccermitchy awesome! thanks! I really like .NET Core too, but I can afford to use the normal .NET Framework because I have a Windows machine and my Linux machine has a GUI.

**Comment by soccermitchy** [comment]
Have a project.json that could be used now when I get SharpJS recompiled with .net core:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "SharpJS": "1.6.3",
    "NETStandard.Library": "1.6.0"
  },
  "frameworks": {
    ".NETStandard,Version=v1.6": {
      "dependencies": {
          "NETStandard.Library": "1.6.0"
      },
      "imports": [
        "dnxcore50",
        ".NETFramework,Version=v0.0"
      ]
    }
  },
  "runtimes": {
    "win7-x64": {},
    "win8-x64": {},
    "win81-x64": {},
    "win10-x64": {},
    "osx.10.11-x64": {},
    "ubuntu.16.04-x64": {}
  }
}
```

Error I get when I build with this configuration:
```
mitchell@ubuntu:~/code/sharpjs-dnx$ dotnet build
Project sharpjs-dnx (.NETStandard,Version=v1.6) will be compiled because expected outputs are missing
Compiling sharpjs-dnx for .NETStandard,Version=v1.6
/usr/share/dotnet/dotnet compile-csc @/home/mitchell/code/sharpjs-dnx/obj/Debug/netstandard1.6/dotnet-compile.rsp returned Exit Code 1
/home/mitchell/code/sharpjs-dnx/MainForm.cs(11,29): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:01.3351179
```

**Comment by 0xFireball** [comment]
So it's not finding `mscorlib`? I'm not sure, but I'm guessing there's a framework mismatch from the error message.

As for recompiling SharpJS with .NET Core, we probably only need to modify the projects in the `ExaPhaser` folder, because a lot of the rest is just JSIL.

Also, we'll need to fork [Meta](https://github.com/sq/JSIL.Meta) and update the submodule.

**Comment by 0xFireball** [comment]
I'm going to be a bit busy soon, so I probably won't get to doing anything myself until the end of the week. If you happen to get it working though, send a pull request, and I'll merge it.

As for Meta, it might even be easier to just leave the [current csproj](https://github.com/sq/JSIL.Meta/blob/b185a3d1a30e6d580456e6d78eaf07f0b06a13bb/Meta.csproj) alone and just add another `JSIL.Meta.NetCore.csproj` targeting .NET Core

If you can, keep me updated! I might have a bit of time tomorrow.

**Comment by soccermitchy** [comment]
Actually, `Meta` was pretty easy to port. Right now I'm having an issue with `ICSharpCode.NRefactory` needing `IClonable`, which was removed in .net core apparently. Only 23 errors right now on that project though:
```
mitchell@ubuntu:~/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory$ dotnet build
Project ICSharpCode.NRefactory (.NETStandard,Version=v1.6) will be compiled because expected outputs are missing
Compiling ICSharpCode.NRefactory for .NETStandard,Version=v1.6
/usr/share/dotnet/dotnet compile-csc @/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/obj/Debug/netstandard1.6/dotnet-compile.rsp returned Exit Code 1
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/IAnnotatable.cs(109,47): error CS0246: The type or namespace name 'ICloneable' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Documentation/XmlDocumentationProvider.cs(211,19): error CS0246: The type or namespace name 'XmlTextReader' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Documentation/XmlDocumentationProvider.cs(268,34): error CS0246: The type or namespace name 'XmlTextReader' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(37,10): error CS0246: The type or namespace name 'SerializationBinder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(442,22): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(442,38): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(459,26): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(683,23): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(683,39): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(683,60): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(709,28): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(748,27): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(748,43): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1191,22): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1191,38): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1191,59): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1217,27): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1217,43): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1257,26): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1257,42): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(763,3): error CS0246: The type or namespace name 'FormatterConverter' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/TypeSystem/ReflectionNameParseException.cs(57,24): error CS0115: 'ReflectionNameParseException.GetObjectData(SerializationInfo, StreamingContext)': no suitable method found to override
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/TypeSystem/Implementation/AbstractFreezable.cs(73,67): error CS0246: The type or namespace name 'ICloneable' could not be found (are you missing a using directive or an assembly reference?)

Compilation failed.
    0 Warning(s)
    23 Error(s)

Time elapsed 00:00:01.3448139
```

**Comment by 0xFireball** [comment]
Yep, unfortunately it looks like ICloneable is now bad practice.

I'll look at the issue too later today

- NT



On Sun, Oct 9, 2016 at 8:30 AM -0700, "Mitchell Monahan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, Meta was pretty easy to port. Right now I'm having an issue with ICSharpCode.NRefactory needing IClonable, which was removed in .net core apparently. Only 23 errors right now on that project though:

mitchell@ubuntu:~/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory$ dotnet build
Project ICSharpCode.NRefactory (.NETStandard,Version=v1.6) will be compiled because expected outputs are missing
Compiling ICSharpCode.NRefactory for .NETStandard,Version=v1.6
/usr/share/dotnet/dotnet compile-csc @/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/obj/Debug/netstandard1.6/dotnet-compile.rsp returned Exit Code 1
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/IAnnotatable.cs(109,47): error CS0246: The type or namespace name 'ICloneable' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Documentation/XmlDocumentationProvider.cs(211,19): error CS0246: The type or namespace name 'XmlTextReader' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Documentation/XmlDocumentationProvider.cs(268,34): error CS0246: The type or namespace name 'XmlTextReader' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(37,10): error CS0246: The type or namespace name 'SerializationBinder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(442,22): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(442,38): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(459,26): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(683,23): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(683,39): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(683,60): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(709,28): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(748,27): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(748,43): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1191,22): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1191,38): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1191,59): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1217,27): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1217,43): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1257,26): error CS0246: The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(1257,42): error CS0246: The type or namespace name 'LocalBuilder' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/Utils/FastSerializer.cs(763,3): error CS0246: The type or namespace name 'FormatterConverter' could not be found (are you missing a using directive or an assembly reference?)
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/TypeSystem/ReflectionNameParseException.cs(57,24): error CS0115: 'ReflectionNameParseException.GetObjectData(SerializationInfo, StreamingContext)': no suitable method found to override
/home/mitchell/code/ported-sharpjs/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/TypeSystem/Implementation/AbstractFreezable.cs(73,67): error CS0246: The type or namespace name 'ICloneable' could not be found (are you missing a using directive or an assembly reference?)

Compilation failed.
    0 Warning(s)
    23 Error(s)

Time elapsed 00:00:01.3448139


-

**Comment by soccermitchy** [comment]
Just heard from one of my friends that .Net Core is moving back to .csproj files later on, so I may as well not put in the effort for converting everything to project.json files now... In the meantime, I think I got the memory usage of MonoDevelop down by reinstalling the package, so I'll at least try using that, and when the update that uses .csproj files is released for .net core, I'll resume porting everything.

**Comment by 0xFireball** [comment]
Great!
I've temporarily paused work on NeptuniumKit, which will allow XAML-like UI with SharpJS.

I'm still trying to decide on how I should implement the XAML tool; keeping it cross platform would create issues with IntelliSense, but an IDE plugin wouldn't work with command line users.

I'm leaning toward an MSBuild solution that should be cross platform. I believe the new .NET core update will go back to MSBuild anyway.

- NT



On Tue, Oct 11, 2016 at 7:36 PM -0700, "Mitchell Monahan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Just heard from one of my friends that .Net Core is moving back to .csproj files later on, so I may as well not put in the effort for converting everything to project.json files now... In the meantime, I think I got the memory usage of MonoDevelop down by reinstalling the package, so I'll at least try using that, and when the update that uses .csproj files is released for .net core, I'll resume porting everything.

-

**Comment by soccermitchy** [comment]
Pretty sure that's the direction they are going in, I just hope they have a
command line tool for managing projects...
